# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [2]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [22]:
numeros = np.arange(10)
print(type(numeros),":", numeros)


<class 'numpy.ndarray'> : [0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
array_ceros = np.zeros(5)
array_ceros[2] = 5

print(array_ceros)

[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [34]:
matriz_3_3 = np.random.rand(3,3)
print(np.round(matriz_3_3, 2))

[[0.76 0.11 0.69]
 [0.61 0.71 0.36]
 [0.74 0.87 0.9 ]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [44]:
arr = np.array([10, 20, 30, 40, 50])
arr_sum = arr + 5
print(f'El resultado de la suma de 5 a cada elemento de {arr} es: {arr_sum}')
num_random = randint(1, 100)
arr_multi = arr * num_random
print(f'La multiplicación de {num_random} por cada elemento de {arr} es: {arr_multi}')

El resultado de la suma de 5 a cada elemento de [10 20 30 40 50] es: [15 25 35 45 55]
La multiplicación de 36 por cada elemento de [10 20 30 40 50] es: [ 360  720 1080 1440 1800]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [39]:
array_4x4 = np.eye(4)
print(array_4x4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [53]:
arr_pares = np.arange(0, 21, 2)
print(f'''
El array de pares es: {arr_pares}
Los calculos basicos se realizaran con el siguiente numero: {num_random}''')
#SUMA
sum_arr_par = arr_pares + num_random
print(f'La suma dio como resultado {sum_arr_par}')
#RESTA
res_arr_par = arr_pares - num_random
print(f'La resta dio como resultado {res_arr_par}')
#DIVISION 
div_arr_par = arr_pares / num_random
print(f'La division dio como resultado {np.round(div_arr_par, 2)}')
#MULTIPLICACION
multi_arr_par = arr_pares * num_random
print(f'La multiplicacion dio como resultado {multi_arr_par}')



El array de pares es: [ 0  2  4  6  8 10 12 14 16 18 20]
Los calculos basicos se realizaran con el siguiente numero: 36
La suma dio como resultado [36 38 40 42 44 46 48 50 52 54 56]
La resta dio como resultado [-36 -34 -32 -30 -28 -26 -24 -22 -20 -18 -16]
La division dio como resultado [0.   0.06 0.11 0.17 0.22 0.28 0.33 0.39 0.44 0.5  0.56]
La multiplicacion dio como resultado [  0  72 144 216 288 360 432 504 576 648 720]
